### ISSUE TITLE
statically link i2pd_qt on Windows MSYS2 mingw32

### ISSUE THREAD

**Issue by mewmew-i2p** [PurpleI2P/i2pd#1156]
```
../../libi2pd/FS.cpp: In function 'void i2p::fs::DetectDataDir(const string&, bool)':
../../libi2pd/FS.cpp:51:52: error: cannot convert 'char*' to 'LPWSTR {aka wchar_t*}' for argument '2' to 'DWORD GetModuleFileNameW(HMODULE, LPWSTR, DWORD)'
     GetModuleFileName (NULL, localAppData, MAX_PATH);
                                                    ^
../../libi2pd/FS.cpp:59:67: error: cannot convert 'char*' to 'LPWSTR {aka wchar_t*}' for argument '5' to 'HRESULT SHGetFolderPathW(HWND, int, HANDLE, DWORD, LPWSTR)'
         SHGetFolderPath(NULL, CSIDL_APPDATA, NULL, 0, localAppData);
```

**Comment by mewmew-i2p** [comment]
я собрал вчера i2pd_qt под мингв32, но динамически

скопировать все дллки в папку и запустить - не помогло

нада статически видимо собирать

запускается пока что только из консоли мсис2

надо глянуть как гост валлет под винду линкуется

**Comment by r4sas** [comment]
Re: [PurpleI2P/i2pd] i2pd_qt does not build on Windows MSYS2 mingw32 (#1156)


Здравствуйте, mewmew-i2p.

Вы писали 9 апреля 2018 г., 7:32:47:





я собрал вчера i2pd_qt под мингв32, но динамически
скопировать все дллки в папку и запустить - не помогло
нада статически видимо собирать
запускается пока что только из консоли мсис2
надо глянуть как гост валлет под винду линкуется
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



qt надо собирать статично чтобы всё было как надо.

--
С уважением,
 Kirill                          mailto:mxplrskirill@mail.i2p

**Comment by mewmew-i2p** [comment]
now builds for win32
