### ISSUE TITLE
RFC4941 IPV6 addresses shouldn't be published in netdb

### ISSUE THREAD

**Issue by madman2003** [PurpleI2P/i2pd#1251]
i2pd picks IPV6 addresses with very short lifetime, so one or two temporary addresses when the hard expire occurs all IPV6 tunnels collapse. Later new IP is picked up again and published in netdb, and a little while later the problem same happens.

**Comment by orignal** [comment]
It takes ipv6 address to publish from a successive NTCP connection.
Please provide an example.

**Comment by madman2003** [comment]
Basically with IPV6 you have 128 bits address. The lower 64 bits vary within the same network. One address is link local, starting with FE80 (upper 16 bits), not very interesting for global routing. One address will be long term stable and globally routable. Optionally/often there is also at least one temporary address that is valid for X minutes (all addresses share the same upper 64 bits, but usually completely different lower 64 bits). OS prefers the temporary address for newly established outbound communication for privacy reasons, because stable address embeds MAC address in lower 64 bits (using the oldest spec for IPV6 address generation) allowing global tracking of that MAC address in any network (upper 64 bits). Old temporary privacy addresses stay around for a while as deprecated, but eventually disappear.

For IPV6 it is very common to have multiple IP addresses at any given time, and you can communicate with all of them. Checking  a random outbound connection for IP is not reliable for server purposes, because the address can expire within 5-10 minutes. Java I2P has some protections to select long term stable address, although it may be OS dependent.

**Comment by l-n-s** [comment]
@orignal but what if we don't have SSU enabled?

Looks like OP is proposing to add some address  sanity checking, so that we don't add "temporary privacy addresses" to RouterInfo.

**Comment by orignal** [comment]
if no SSU, somebody has to specify it explicitly

**Comment by madman2003** [comment]
@l-n-s My suggestion was to do some sanity checking, but I'm here to raise awareness about a problem, not dictate solutions. I was just surprised to see i2pd not working well for IPV6, which I isolated to the router info containing an invalid ip, which previously had been a temporary address.

**Comment by r4sas** [comment]
>20:15 <~R4SAS> https://tools.ietf.org/html/rfc4941
20:16 <~R4SAS> #section-3.3
20:18 <~R4SAS> https://stackoverflow.com/questions/35442119/find-temporary-ipv6-address-using-getadaptersaddresses
20:24 <~R4SAS> https://stackoverflow.com/questions/17833765/detect-temporary-ipv6-address-crossplatform
20:29 <~orignal> R4SAS на самом деле правильный путь
20:29 <~orignal> это делать PeerTest для v6 и брать оттуда
20:30 <~R4SAS> ясное дело
20:30 <~R4SAS> но это не факт что адрес будет корректным
20:30 <~R4SAS> ибо исходящий может происходить с временного
20:30 <~R4SAS> такова соль этого 4941
20:31 <~orignal> и че делать?
20:36 <~R4SAS> #section-3.1
20:36 <~R4SAS> [ADDR_SELECT] mandates implementations to provide a mechanism, which
20:36 <~R4SAS>    allows an application to configure its preference for temporary
20:36 <~R4SAS>    addresses over public addresses.  It also allows for an
20:36 <~R4SAS>    implementation to prefer temporary addresses by default, so that the
20:36 <~R4SAS>    connections initiated by the node can use temporary addresses without
20:36 <~R4SAS>    requiring application-specific enablement.
20:37 <~R4SAS> 20:31 <~orignal> и че делать?
20:37 <~R4SAS> This document also assumes that an API will exist that allows individual applications to indicate
               whether they prefer to use temporary or public addresses and override the system defaults.
20:37 <~R4SAS> искать
20:40 <~R4SAS> https://tools.ietf.org/html/rfc6724
20:41 <~R4SAS> #section-5
20:41 <~R4SAS> Implementations MUST provide a mechanism allowing an application to reverse the sense of this
               preference and prefer public addresses over temporary addresses (e.g., via appropriate API
               extensions such as [RFC5014])
20:43 <~R4SAS> https://tools.ietf.org/html/rfc5014
20:44 <~R4SAS> #section-5
20:44 <~R4SAS> IPV6_PREFER_SRC_PUBLIC /* Prefer Public address as source */
20:45 <~R4SAS> #section-8, #section-9
20:45 <~R4SAS> примеры

**Comment by r4sas** [comment]
WinSock doesn't support IPV6_ADDR_PREFERENCES options.
https://docs.microsoft.com/en-us/windows/desktop/WinSock/socket-options
