### ISSUE TITLE
What do "probabalistic backoff" mean of limits.ntcpsoft in i2pd documentation?

### ISSUE THREAD

**Issue by tsr7r3tss5ulwod8** [PurpleI2P/i2pd#1310]
https://i2pd.readthedocs.io/en/latest/user-guide/configuration/#limits

**Comment by orignal** [comment]
ping  @majestrate

**Comment by majestrate** [comment]
On Tue, Mar 19, 2019 at 04:22:10AM -0700, orignal wrote:
> ping  @majestrate 

it's a way to do soft limiting on the number of connections, instead of having a hard cutoff you
probabilistically (randomly) deny new connections with the probability going up as you have more 
connections. that argument enables that and adds a parameter to tune that behavior with.
