### ISSUE TITLE
HTTP/2 support in HTTP proxy

### ISSUE THREAD

**Issue by za3ter2p** [PurpleI2P/i2pd#1377]
I2P-Java is based on the old HTTP , and responded as wont fix to migrate/support HTTP/2:

https://trac.i2p2.de/ticket/1511

Is i2pd willing to support it ? (look at the links inside that ticket for further benefits)

Side Note: There is as well HTTP/3 :

https://daniel.haxx.se/blog/2018/11/11/http-3/

**Comment by r4sas** [comment]
Is that really needed?

**Comment by l-n-s** [comment]
I also doubt that it's relevant to upgrade HTTP protocols in I2P. 

HTTP/2 main advantage is reduced latency, which makes no sense in I2P (we have latencies like 2000ms anyway).

Also, web browsers enforce TLS connections for HTTP/2. I2P is end-to-end encrypted by design and adding extra TLS is unnecessary overhead/complexity.

**Comment by orignal** [comment]
As I remember, the main advantage for HTTP/2  you can download entire content through a single stream

**Comment by r4sas** [comment]
In that case I think better use Socks proxy, because all communications will be in binary type.

**Comment by r4sas** [comment]
If someone implement this without external dependencies and PR it, we'll think about it.
