### ISSUE TITLE
Does not compile under old x86

### ISSUE THREAD

**Issue by neheb** [PurpleI2P/i2pd#1600]
https://downloads.openwrt.org/snapshots/faillogs/i386_pentium-mmx/packages/i2pd/compile.txt

It seems it wrongly determines that march=pentium-mmx supports AVX.

**Comment by r4sas** [comment]
Can you get all preprocessor defines provided for this target?
Use this: https://stackoverflow.com/a/2224357.

**Comment by r4sas** [comment]
Please try this: https://github.com/PurpleI2P/i2pd/commit/ca3b8191510c1006d031d02c50edcf6b4f6a6e8f

**Comment by neheb** [comment]
That did not fix it. https://github.com/openwrt/packages/pull/14192

i386_pentium-mmx is still failing with the same error.

**Comment by r4sas** [comment]
That's why I'm asking you to get somehow preprocessor defines.

**Comment by neheb** [comment]
I tried as best as I could to get the defines.

https://gist.github.com/neheb/964f6207b91a6047503bb864df3e6b9f

**Comment by neheb** [comment]
So that patch partially works. The Issue is now

```
libi2pd/Identity.cpp:834:4: error: the register '%xmm1' cannot be clobbered in 'asm' for the current target
  834 |    __asm__
```

I think fixing that avx variable is the correct solution.

**Comment by neheb** [comment]
Meh I gave up. I applied the same workaround for that section.

**Comment by r4sas** [comment]
> I tried as best as I could to get the defines.

Huh, too much defines after running `i486-openwrt-linux-musl-g++ -march=pentium-mmx -dM -E -x c++ - < /dev/null`?

> I think fixing that avx variable is the correct solution.

I think you trying to build with `USE_AESNI` enabled, so solution is setting it to `no` and previous patch.
If setting it to `no` still continues use of AES registers, that can be assumed as compiler bug, because it musn't add `__AES__` define if it is not suported by target architecture.
