### ISSUE TITLE
Crashing on server side when I connect via client tunnel

### ISSUE THREAD

**Issue by arleenlasleur** [PurpleI2P/i2pd#1755]
I tried some tunnels (vnc) between my machines and sometimes i2pd crashed.

The crash happens on remote machine (client tunnel destination), right in moment of connect.

If I restart it, can be working normally (without crashes).

What can I write in log level to collect more data? Do you need Windows Events log or something like this?

**Comment by r4sas** [comment]
Is server side on windows?

**Comment by arleenlasleur** [comment]
Yes, Win7 SP1.

**Comment by r4sas** [comment]
Due to using MinGW for windows, you must set up MSYS2 environment and run i2pd inside gdb to catch a crash, because Windows Error reporting won't say anything interesting.

Also, can you try trunk build from Actions? Use x64-crt runtime from that build as example: https://github.com/PurpleI2P/i2pd/actions/runs/2327656164
