### ISSUE TITLE
Enable Docker users to access i2pd.conf

### ISSUE THREAD

**Issue by count-null** [PurpleI2P/i2pd#1788]
I see that the directory /home/i2pd/data is used, but I cannot find any file named i2pd.conf in the docker image. Where is the config for docker image? A note for how to edit config options in docker should be in the docs.

**Comment by r4sas** [comment]
According to [Dockerfile](https://github.com/PurpleI2P/i2pd/blob/openssl/contrib/docker/Dockerfile), there is no i2pd.conf inside container.

**Comment by count-null** [comment]
Thanks, how should docker users add their configuration options, then?

**Comment by r4sas** [comment]
You can create i2pd.conf in /home/i2pd/data and fill it, but [options](https://github.com/PurpleI2P/i2pd/blob/openssl/contrib/docker/Dockerfile#L14) provided in Dockerfile will be ignored in file.

**Comment by Danie10** [comment]
Glad I found this logged issue. I seem to be having a similar issue in that the official docker image looks for /home/i2pd/data for the i2pd.conf file.  It ignores the /var/lib/i2pd volume I had mapped for. So I gave it what it wanted, and I instead mapped the volume to /home/i2pd/data. It then created all its files along with a default i2pd.conf.

But it creates them as a user ID i2pd and not root as is the norm. So a redirect that is in that /home/i2pd/data folder points to a certificates file in the root / and of course there are no permissions to access that.

The browser access port 7070 reports host mismatch so I'm not sure if it is reading its config file correctly.

I really do wish there was an official guide to how the docker set up should work, along with relevant environment settings for example port address etc. I have tried binding mine to 0.0.0.0 in the config file, but it does not seem to have made a difference.

Ideally the docker image should default to /var/lib/i2pd rather than a user home directory. I did manage to get I2P up and going in Docker, and I was hoping to switch top I2PD, but without it showing any errors in the log file (says starting), it is difficult to know what to fix now.
