### ISSUE TITLE
corrupted double-linked list

### ISSUE THREAD

**Issue by timewall** [PurpleI2P/i2pd#226]
get http://127.0.0.1:7070/zmw2cyw2vj7f6obx3msmdvdepdhnw2ctc4okza2zjxlukkdfckhq.b32.i2p

then

*** Error in `src/i2pd/./i2p': corrupted double-linked list: 0x00007fcee40053b0 ***
terminate 

This error occurs at random and can not be reproduced but he always comes back

15:16:57/debug - Process SSU data flags=128 len=11
15:16:57/debug - Process SSU data flags=128 len=11
15:16:57/debug - Process SSU data flags=128 len=11
15:16:57/debug - Process SSU data flags=128 len=11
15:16:57/debug - Process SSU data flags=128 len=91
15:16:57/debug - Process SSU data flags=128 len=27
15:16:57/debug - Process SSU data flags=128 len=27
15:16:57/debug - Process SSU data flags=4 len=1051
15:16:57/info - TunnelMessage: handle fragment of 28 bytes. Msg type 10
15:16:57/info - DeliveryStatus
15:16:57/info - Tunnel test 3770142043 successive. 598 milliseconds
15:16:57/debug - Process SSU data flags=128 len=107
15:16:57/debug - Process SSU data flags=128 len=27
15:16:58/debug - Process SSU data flags=128 len=139
15:16:58/debug - Process SSU data flags=132 len=1083
15:16:58/info - TunnelMessage: handle fragment of 28 bytes. Msg type 10
15:16:58/info - DeliveryStatus
15:16:58/info - Tunnel test 576081208 successive. 857 milliseconds
15:16:58/debug - Process SSU data flags=128 len=91
15:16:58/debug - Process SSU data flags=132 len=1083
15:16:58/info - TunnelMessage: handle fragment of 276 bytes. Msg type 11
15:16:58/info - Garlic
15:16:58/info - 1 cloves
15:16:58/info - Garlic type destination
15:16:58/info - Unknown stream sendStreamID=2704565499
15:16:58/debug - Process SSU data flags=128 len=27
15:16:58/debug - Process SSU data flags=132 len=1067
15:16:58/info - TunnelMessage: handle fragment of 28 bytes. Msg type 10
15:16:58/info - DeliveryStatus
15:16:58/info - Tunnel test 1973231619 successive. 762 milliseconds
15:16:58/debug - Process SSU data flags=132 len=1067
15:16:58/info - TunnelMessage: handle fragment of 28 bytes. Msg type 10
15:16:58/info - DeliveryStatus
15:16:58/info - Tunnel test 1651784004 successive. 1238 milliseconds
15:17:00/debug - Process SSU data flags=132 len=1083
15:17:00/info - TunnelMessage: handle fragment of 276 bytes. Msg type 11
15:17:00/info - Garlic
15:17:00/info - 1 cloves
15:17:00/info - Garlic type destination
15:17:00/info - Unknown stream sendStreamID=2704565499
*** Error in `src/i2pd/./i2p': corrupted double-linked list: 0x00007f18c4005bb0 ***
Abgebrochen

**Comment by orignal** [comment]
This code might not work properly. You should use HTTP proxy instead

**Comment by EinMByte** [comment]
Verified that it doesn't work, nevertheless this should be fixed.

**Comment by gluk47** [comment]
That's funny. Then you should update the project README, because now it states the following:
====
To visit an I2P page, you need to find the b32 address of your destination. After that, go to the webconsole and add it behind the url. (Remove http:// from the address)

This should resulting in for example: http://localhost:7070/4oes3rlgrpbkmzv4lqcfili23h3cvpwslqcfjlk6vvguxyggspwa.b32.i2p
====
That is, nothing about a proxy.
How do we actually use it?
I tried to use HTTP proxy on the port 7070,
got the following response in a browser:
'Unknown address ttp:' (I tried several browsers) alongside with the purple man.

The console log is:
HTTP Client Request: GET //zmw2cyw2vj7f6obx3msmdvdepdhnw2ctc4okza2zjxlukkdfckhq.b32.i2p/ HTTP/1.1
Host:ttp:

**Comment by orignal** [comment]
Will do.
Proxy port is 4446

**Comment by orignal** [comment]
fixed
