### ISSUE TITLE
Ctrl-C could not kill foreground process (started with -daemon=0)

### ISSUE THREAD

**Issue by blacklion** [PurpleI2P/i2pd#289]
Looks like this:

21:29:57/info - Downloading SU3 from https://reseed.i2p-projekt.de/
^C^C^C
^C^C^C
21:32:27/error - Can't connect to reseed.i2p-projekt.de:443
21:32:27/warn - SU3 download failed
21:32:27/info - Downloading SU3 from http://i2p-netdb.innovatio.no/
21:32:27/info - HTTP response 404
21:32:27/warn - SU3 download failed
21:32:27/info - Downloading SU3 from http://netdb.i2p2.no/
^C^C^C^C
^C^C^C^C
^C^C^C^C
21:33:42/info - HTTP response 410

(FreeBSD 10-STABLE, latest github commit)

**Comment by blacklion** [comment]
Ok, it was terminated after all failed attempts to re-seed.

**Comment by orignal** [comment]
Reseeds lists has been changed, but master still contains old. The reason is that implementation of TLS supports RSA chiphers only, shared key has never been implemented. And since I have switched to openssl, no reason to have own SSL.
The my concern is  "Can't connect to reseed.i2p-projekt.de:443".
Looks like you tried to reseed from there many times and have been banned.,

**Comment by blacklion** [comment]
Non-working for long time ^C is what bother me, not long re-seeding per se.

BTW, switched to OpenSSL?! In 2016^H5?! Are you serious?! Not LibreSSL, not mbed TLS (former PolarSSL), not GnuTLS, not NSS, but OpenSSL?!

**Comment by orignal** [comment]
The reason for openssl is most of cryptocoins use openssl, since they are all forks of bitcoins.
Also libcrypto is available almost everywhere by default.
SSL is a smaller part
