### ISSUE TITLE
2.4.0 version and log file

### ISSUE THREAD

**Issue by SimWhite** [PurpleI2P/i2pd#389]
Hello.

Could you tell what is the correct parameters for the file-based log output? Now I'm tried to use something like below at `/etc/i2pd/i2pd.conf`:

```
log = yes
logfile = /var/log/i2pd.log
loglevel = error
```

But there is no any messages.

**Comment by khumarahn** [comment]
This is really unclear. According to Daemon.cpp, you should use "log=file", not "log=yes". Also, command line options override configuration file, so you should check the command line options in your system
```

			std::string logs     = ""; i2p::config::GetOption("log",      logs);
			std::string logfile  = ""; i2p::config::GetOption("logfile",  logfile);
			std::string loglevel = ""; i2p::config::GetOption("loglevel", loglevel);

			if (isDaemon && (logs == "" || logs == "stdout"))
				logs = "file";

			if (logs == "file") {
				if (logfile == "")
					logfile = i2p::fs::DataDirPath("i2pd.log");
				StartLog (logfile);
			} else {
				// use stdout
				StartLog ("");
			}
			SetLogLevel(loglevel);
```

**Comment by SimWhite** [comment]
I used examples and description from [official guide](http://i2pd.readthedocs.org/en/latest/configuration.html). Also I used original scripts for debian from the [.deb packages](http://i2pd.website/releases/2.4.0/).

**Comment by khumarahn** [comment]
I may be wrong here, but here is my best guess for what happens, after taking a brief look at the source code:
* the option --log is the same as  --log="". It does not do anything, since log="" is the default value anyway
* the config file is read after the command line options, according to Daemon.cpp, and log option is overwritten; command line option does not take priority here de facto, even though it is supposed to; maybe it is because the command line option is the empty default value.
* as a result, after reading your config file, log option becomes "yes"; accoring to Daemon.cpp, this leads to logging to stdout

As a workaround, you should try using "log=file" in your config file. Later these things will probably be rewritten properly.

**Comment by orignal** [comment]
-log=file is correct one, the documentation will be updated shortly

**Comment by khumarahn** [comment]
What is a current mechanism of working with logrotate? Does i2pd have to be restarted after logs are truncated, or there is another way?

**Comment by orignal** [comment]
kill -s HUP and log file will be reopen

**Comment by khumarahn** [comment]
Does debian/logrotate file have to be updated? How?

**Comment by orignal** [comment]
https://github.com/PurpleI2P/i2pd/issues/355
