### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by luveti** [PurpleI2P/i2pd#609]
Are there any plans on bringing this to iOS, or have there been any attempts? I feel like since this is wrote in C++, it may be a bit easier to get running on iOS compared to the Java version.

**Comment by orignal** [comment]
Would Apple allow any I2P in their Apple Store? I doubt.
Otherwise we could try

**Comment by luveti** [comment]
They allow for tor based browsers on there store https://itunes.apple.com/us/app/onion-browser/id519296448?mt=8&at=10l9R4
It looks like it has some problems. But I think that's due to the fact that it's implementing a full browser. An iOS i2p app would be similar to the android version where it runs as a seperate program right?

**Comment by orignal** [comment]
It should be a service app with minimal gui like we have for andorid.

**Comment by mikalv** [comment]
I'm for porting it to any system possible.

I've noticed myself that Tor is on Apple store, or at least a minified version of it. But it's only available in some countries. I guess this is because of american crypto export laws.

Based on my knowledge of how iOS applications work we need to build a browser within the I2Pd app to be able to surf on .i2p pages and such, since applications has a much much more strict communication system on iOS rather than Android.

I'm not a expert on this, but I'm gonna ask a iOS developer who's visiting me after work today to find out how it could be done.

**Comment by l-n-s** [comment]
We support iOS builds now and there is an app called TrekNoir at appstore (currently closed-sourced, but could be open in future)

**Comment by l-n-s** [comment]
@donaldking iOS support was added  #627  by @vovasty back in 2016. Currently, we don't have an iOS dev in i2pd team, you probably know more than me about iOS development...

**Comment by donaldking** [comment]
Ok. I'll look into this and provide a solution 😊
