### ISSUE TITLE
Transports: No NTCP or SSU addresses available

### ISSUE THREAD

**Issue by manasb** [PurpleI2P/i2pd#761]
I ran the latest i2pd for a few days, logs are full of this message - loglevel error

```shell
$ cat i2pd.log | wc -l
  262475
```

```shell
$ grep 'Transports: No NTCP or SSU addresses available' i2pd.log | wc -l
  198882
```

75% of the log file is this message. The log file is about 20 MB. 
I'm going to turn off logging as this kind of logging isn't helpful, not to me at least.

If this is an error in configuration or otherwise on my side, please let me know.

Thanks.

**Comment by orignal** [comment]
If too many (vs. success), it means something wrong with your network

**Comment by kalle999** [comment]
I have exactly the same problem.
@orignal can you give me advise what I may ask my ISP to fix this? They often say that everything is fine, so I have to do it in a clever way, that they really care about this issue.

**Comment by orignal** [comment]
how is it related to ISP? Nothing to do with them

**Comment by kalle999** [comment]
Well I what do you mean with 'something is wrong with your network' then? And how to fix it?

**Comment by orignal** [comment]
I said "if". What is your problem?

**Comment by majestrate** [comment]
i think that message is sent when i2pd can't connect to another router,
incorrect log level/message?

**Comment by kalle999** [comment]
> I said "if". The first thing you should check is your clock.
What is your problem?

Date is correct and sync. Tor (which requires correct clock settings) is working without problems too.
My problem actually is, that the logfile size increases to heavy because it is full of this message. Log level is set to 'error'.

> 13:37:37@922/error - Transports: No NTCP or SSU addresses available
13:37:38@922/error - Transports: No NTCP or SSU addresses available
13:37:38@922/error - Transports: No NTCP or SSU addresses available
13:37:46@620/error - SSU: unexpected message 1
13:37:51@922/error - Transports: No NTCP or SSU addresses available
13:37:57@922/error - Transports: No NTCP or SSU addresses available
13:38:02@922/error - Transports: No NTCP or SSU addresses available
13:38:11@922/error - Transports: RouterInfo not found, Failed to send messages
13:38:14@922/error - Transports: No NTCP or SSU addresses available
13:38:21@922/error - Transports: No NTCP or SSU addresses available
13:38:23@922/error - Transports: No NTCP or SSU addresses available
13:38:29@922/error - Transports: No NTCP or SSU addresses available
13:38:31@922/error - Transports: No NTCP or SSU addresses available
13:38:33@922/error - Transports: No NTCP or SSU addresses available
**13:38:42@989/error - NTCP: Phase 4 read error: End of file. Check your clock**
13:38:47@922/error - Transports: No NTCP or SSU addresses available
13:38:48@922/error - Transports: No NTCP or SSU addresses available
13:38:53@989/error - NTCP: Connected from error Transport endpoint is not connected
13:39:00@922/error - Transports: No NTCP or SSU addresses available
13:39:04@791/error - NetDb: database store with own RouterInfo received, dropped
13:39:17@922/error - Transports: No NTCP or SSU addresses available
13:39:32@922/error - Transports: No NTCP or SSU addresses available
13:39:35@922/error - Transports: No NTCP or SSU addresses available
13:39:40@922/error - Transports: No NTCP or SSU addresses available
13:39:42@620/error - SSU: unexpected message 1
13:39:53@922/error - Transports: No NTCP or SSU addresses available
13:39:54@620/error - SSU message 'confirmed' signature verification failed
13:40:00@922/error - Transports: No NTCP or SSU addresses available
13:40:04@922/error - Transports: No NTCP or SSU addresses available
13:40:05@922/error - Transports: No NTCP or SSU addresses available
13:40:07@922/error - Transports: No NTCP or SSU addresses available
13:40:10@922/error - Transports: No NTCP or SSU addresses available
13:40:13@922/error - Transports: No NTCP or SSU addresses available
13:40:14@922/error - Transports: No NTCP or SSU addresses available
13:40:14@922/error - Transports: No NTCP or SSU addresses available

As you see, it indeed tells me to check clock, but as I said theres nothing wrong.

**Comment by orignal** [comment]
Again, what's a problem beside these messages in the log?

**Comment by kalle999** [comment]
Exept the file size of the logfile, I noticed a massive increase of the serverload after ~2 hours. CPU load jumps for no obvious reason to 100% and stays there. Before it is always between 5% and 25%. No changes happen in the logfile.

bandwith = X (tested O and P too, but no changes)
transittunnels = 2500 (tested 1000, but no changes)

**Comment by majestrate** [comment]
the cpu load jump may be related to hitting the open file limit by OS.
still hunting for that

**Comment by kalle999** [comment]
@majestrate Thanks for this high quality comment, I increased the open file limit and will monitor now if it helps.

**Comment by l-n-s** [comment]
@manasb Seems to be solved.

[Recent commit](https://github.com/PurpleI2P/i2pd/commit/3e2605490f1b2f299b17eb85513e17197d767435) should reduce log size even more.
