### ISSUE TITLE
Docker image exposes all ports to the network by default (including sensitive)

### ISSUE THREAD

**Issue by l-n-s** [PurpleI2P/i2pd#815]
IRC user reports that if you use Docker image, it exposes Web console to all network interfaces by default. 

So, to run Docker image securely, users need to run like that:

     docker run -d -p 127.0.0.1:7070:7070

Maybe not expose any ports by default at all?

ping @meeh420 @mikalv

**Comment by mikalv** [comment]
Yes, that obvious, at least for me, but I see your point that it's not necessary obvious for everyone. We can always update the docs, but I would also then ask people to actually understand how docker works before they start use it, since this is a "global" docker problem since all kinds of containers do it. 

Meaning I'm thinking that if they had anything to hide, they would fuckup on a mysql docker image as well..

In my user case `-p 127.0.0.1:7070:7070` wouldn't work, because my routers are deployed into a kubernetes/origin cluster, or in another (V/VX)LAN solution I have full control over - and it's for sure not exposed out on the wild internet.

**Comment by l-n-s** [comment]
All right, now when I learned more about Docker it become obvious for me that it's not an issue.

@mikalv btw where can I find sources for https://hub.docker.com/r/meeh/i2pd/ ? Is there a repo?

I've composed alternative Dockerfile for i2pd, with verbose instructions [here](https://github.com/l-n-s/i2pd-docker). It allows building from specific git branch and tags, based on Debian tho, so probably heavier.
